<?php

/**
 * PluginCheckIn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opCheckInPlugin
 * @subpackage model
 * @author     Hiromi Hishida<info@77-web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginCheckIn extends BaseCheckIn
{
 /**
  * whether the specified member can read it
  * @access public
  * @param integer $memberId  null if alian
  * @return boolean
  */
  public function isVisible($memberId)
  {
    $minPublicFlag = $this->getTable()->getMinPublicFlag($this->getMemberId(), $memberId);
    
    return $minPublicFlag <= $this->getPublicFlag();
  }
  
 /**
  * @access public
  * @return boolean
  */
  public function isOpen()
  {
    return $this->getPublicFlag() == CheckInTable::PUBLIC_FLAG_OPEN;
  }
}