<?php

/**
 * PluginCheckInSpotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCheckInSpotTable extends Doctrine_Table
{
 /**
  * pager of spots that is nearby
  * @access public
  * @param float $latitude
  * @param float $longitude
  * @param integer $size
  * @param integer $page
  */
  public function getNearBySpotPager($latitude, $longitude, $size, $page)
  {
    $dummy = new CheckInSpot();
    $dummy->setLatitude($latitude);
    $dummy->setLongitude($longitude);
    
    $query = $dummy->getDistanceQuery('r', true)->orderby('kilometers');
    
    $max = sfConfig::get('app_op_checkin_plugin_max_km', 30);
    if(0 != $max)
    {
      $query->having('kilometers < ?', $max);
    }
    
    return $this->generatePager($query, $size, $page);
  }
  
 /**
  * generates a pager for specified query
  * @access protected
  * @param Doctrine_Query $query a query
  * @param integer $size limit of pager
  * @param integer $page current page
  * @retrn object sfDoctrinePager
  */
  protected function generatePager(Doctrine_Query $query, $size, $page)
  {
    $pager = new sfDoctrinePager('CheckInSpot', $size);
    $pager->setQuery($query);
    $pager->setPage($page);
    $pager->init();
    
    return $pager;
  }
}