<?php

/**
 * PluginCheckInSpot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opCheckInPlugin
 * @subpackage model
 * @author     Hiromi Hishida<info@77-web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginCheckInSpot extends BaseCheckInSpot
{
 /**
  * count up check-in count
  * @access public
  */
  public function upCheckInCount()
  {
    Doctrine_Query::create()->update('CheckInSpot s')->set('s.checkin_count', 's.checkin_count + 1')->where('s.id = ?', $this->getId())->execute();
  }
  
}