<?php

/**
 * PluginCheckInCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCheckInCommentTable extends Doctrine_Table
{
 /**
  * pager of comment for specified check-in
  * @access public
  * @param integer $checkInId  target check-in id
  * @param integer $size limit of pager
  * @param integer $page current page
  * @return object sfDoctrinePager
  */
  public function getCheckInPager($checkInId, $size, $page)
  {
    $query = $this->createQuery('cm')->addWhere('cm.check_in_id = ?', $checkInId)->orderBy('cm.number');
    
    return $this->generatePager($query, $size, $page);
  }
  
 /**
  * generates a pager for specified query
  * @access protected
  * @param Doctrine_Query $query a query
  * @param integer $size limit of pager
  * @param integer $page current page
  * @retrn object sfDoctrinePager
  */
  protected function generatePager(Doctrine_Query $query, $size, $page)
  {
    $pager = new sfDoctrinePager('CheckInComment', $size);
    $pager->setQuery($query);
    $pager->setPage($page);
    $pager->init();
    
    return $pager;
  }
  
 /**
  * check if the member has unread comment
  * @access public
  * @param integer $memberId  current member id
  * @return boolean
  */
  public function hasUnread($memberId)
  {
    return $this->createQuery('cm')->leftJoin('cm.CheckIn ci')->addWhere('ci.member_id = ?', $memberId)->addWhere('cm.has_read = ?', false)->count() > 0;
  }
  
  
 /**
  * mark all the comments on the specified check-in as read
  * @access public
  * @param integer $checkInId id of target check-in
  * @return void
  */
  public function markAllRead($checkInId)
  {
    Doctrine_Query::create()->update('CheckInComment cm')->set('cm.has_read', true)->addWhere('cm.check_in_id = ?', $checkInId)->execute();
  }
}