checkInFriendList:
  caption:
    ja_JP: "%friend%の最新%checkin%"
  description:
    ja_JP: "%friend%の%checkin%を新着順に表示します。"
  component: [checkIn, friendRecentList]
  config:
    max:
      Name:      "max"
      Caption:   "最大表示件数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    5
      Choices:
        1: 1
        3: 3
        5: 5
        7: 7
        10: 10

checkInSnsList:
  caption:
    ja_JP: "全体の最新%checkin%"
  description:
    ja_JP: "全体の%checkin%を新着順に表示します。"
  component: [checkIn, snsRecentList]
  config:
    max:
      Name:      "max"
      Caption:   "最大表示件数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    5
      Choices:
        1: 1
        3: 3
        5: 5
        7: 7
        10: 10
