checkInMemberList:
  caption:
    ja_JP: "最新チェックイン"
  description:
    ja_JP: "メンバーのチェックインを新着順に表示します。"
  component: [checkIn, memberRecentList]
  config:
    max:
      Name:      "max"
      Caption:   "最大表示件数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    5
      Choices:
        1: 1
        3: 3
        5: 5
        7: 7
        10: 10
