checkInMyList:
  caption:
    ja_JP: "自分の最新チェックイン"
  description:
    ja_JP: "自分のチェックインを新着順に表示します。"
  component: [checkIn, myRecentList]
  config:
    max:
      Name:      "max"
      Caption:   "最大表示件数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    5
      Choices:
        1: 1
        3: 3
        5: 5
        7: 7
        10: 10

checkInFriendList:
  caption:
    ja_JP: "マイフレンドの最新チェックイン"
  description:
    ja_JP: "マイフレンドのチェックインを新着順に表示します。"
  component: [checkIn, friendRecentList]
  config:
    max:
      Name:      "max"
      Caption:   "最大表示件数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    5
      Choices:
        1: 1
        3: 3
        5: 5
        7: 7
        10: 10

checkInSnsList:
  caption:
    ja_JP: "全体の最新チェックイン"
  description:
    ja_JP: "全体のチェックインを新着順に表示します。"
  component: [checkIn, snsRecentList]
  config:
    max:
      Name:      "max"
      Caption:   "最大表示件数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    5
      Choices:
        1: 1
        3: 3
        5: 5
        7: 7
        10: 10
